### ISSUE TITLE
npm run dev  error

### ISSUE THREAD

**Issue by zuooo** [MarkMindLtd/Mark-Mind#1]
Html Webpack Plugin:
  ReferenceError: process is not defined
  
  - index.ejs:11 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
  
  - index.ejs:16 module.exports
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
  
  - index.js:284 
    [Mark-Mind]/[html-webpack-plugin]/index.js:284:18
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5

**Comment by zuooo** [comment]
~: npm run dev

> mind@1.1.5 dev /Users/admin/go/src/github.com/MarkMindLtd/Mark-Mind
> node .electron-vue/dev-runner.js

         ___                      __                                                                
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __  __     __   
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\ \/\ \  / ,.`\ 
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\ \ \_\ \/\  __/ 
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \____/\ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/___/  \/____/
                                     \/__/                                                          
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

ℹ ｢wds｣: Project is running at http://localhost:9080/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /Users/admin/go/src/github.com/MarkMindLtd/Mark-Mind/
┏ Renderer Process -----------

  Hash: a1be9a2583a4e5f3ffe9
  Version: webpack 4.42.1
  Time: 8692ms
  Built at: 2020/11/20 上午10:35:03
                                             Asset       Size    Chunks             Chunk Names
                                              0.js    176 KiB         0  [emitted]  
                                              1.js    272 KiB         1  [emitted]  
                                              2.js    167 KiB         2  [emitted]  
                                              3.js   55.2 KiB         3  [emitted]  
                                              4.js   45.4 KiB         4  [emitted]  
                                              5.js   30.1 KiB         5  [emitted]  
                fonts/KaTeX_AMS-Regular--fonts.ttf   69.3 KiB            [emitted]  
               fonts/KaTeX_AMS-Regular--fonts.woff     38 KiB            [emitted]  
              fonts/KaTeX_AMS-Regular--fonts.woff2   32.2 KiB            [emitted]  
           fonts/KaTeX_Caligraphic-Bold--fonts.ttf   18.9 KiB            [emitted]  
          fonts/KaTeX_Caligraphic-Bold--fonts.woff   11.4 KiB            [emitted]  
         fonts/KaTeX_Caligraphic-Bold--fonts.woff2   10.2 KiB            [emitted]  
        fonts/KaTeX_Caligraphic-Regular--fonts.ttf   18.2 KiB            [emitted]  
       fonts/KaTeX_Caligraphic-Regular--fonts.woff   11.2 KiB            [emitted]  
      fonts/KaTeX_Caligraphic-Regular--fonts.woff2     10 KiB            [emitted]  
               fonts/KaTeX_Fraktur-Bold--fonts.ttf   34.8 KiB            [emitted]  
              fonts/KaTeX_Fraktur-Bold--fonts.woff   22.1 KiB            [emitted]  
             fonts/KaTeX_Fraktur-Bold--fonts.woff2   19.9 KiB            [emitted]  
            fonts/KaTeX_Fraktur-Regular--fonts.ttf   33.5 KiB            [emitted]  
           fonts/KaTeX_Fraktur-Regular--fonts.woff   21.6 KiB            [emitted]  
          fonts/KaTeX_Fraktur-Regular--fonts.woff2   19.3 KiB            [emitted]  
                  fonts/KaTeX_Main-Bold--fonts.ttf   59.4 KiB            [emitted]  
                 fonts/KaTeX_Main-Bold--fonts.woff   34.6 KiB            [emitted]  
                fonts/KaTeX_Main-Bold--fonts.woff2   29.5 KiB            [emitted]  
            fonts/KaTeX_Main-BoldItalic--fonts.ttf   43.5 KiB            [emitted]  
           fonts/KaTeX_Main-BoldItalic--fonts.woff   24.8 KiB            [emitted]  
          fonts/KaTeX_Main-BoldItalic--fonts.woff2   21.4 KiB            [emitted]  
                fonts/KaTeX_Main-Italic--fonts.ttf   46.5 KiB            [emitted]  
               fonts/KaTeX_Main-Italic--fonts.woff   25.6 KiB            [emitted]  
              fonts/KaTeX_Main-Italic--fonts.woff2   22.2 KiB            [emitted]  
               fonts/KaTeX_Main-Regular--fonts.ttf   67.9 KiB            [emitted]  
              fonts/KaTeX_Main-Regular--fonts.woff   37.2 KiB            [emitted]  
             fonts/KaTeX_Main-Regular--fonts.woff2   31.7 KiB            [emitted]  
            fonts/KaTeX_Math-BoldItalic--fonts.ttf   38.4 KiB            [emitted]  
           fonts/KaTeX_Math-BoldItalic--fonts.woff   21.8 KiB            [emitted]  
          fonts/KaTeX_Math-BoldItalic--fonts.woff2   19.3 KiB            [emitted]  
                fonts/KaTeX_Math-Italic--fonts.ttf     40 KiB            [emitted]  
               fonts/KaTeX_Math-Italic--fonts.woff   22.3 KiB            [emitted]  
              fonts/KaTeX_Math-Italic--fonts.woff2   19.6 KiB            [emitted]  
             fonts/KaTeX_SansSerif-Bold--fonts.ttf   32.9 KiB            [emitted]  
            fonts/KaTeX_SansSerif-Bold--fonts.woff   18.1 KiB            [emitted]  
           fonts/KaTeX_SansSerif-Bold--fonts.woff2   15.4 KiB            [emitted]  
           fonts/KaTeX_SansSerif-Italic--fonts.ttf   30.2 KiB            [emitted]  
          fonts/KaTeX_SansSerif-Italic--fonts.woff   17.2 KiB            [emitted]  
         fonts/KaTeX_SansSerif-Italic--fonts.woff2   14.7 KiB            [emitted]  
          fonts/KaTeX_SansSerif-Regular--fonts.ttf   29.1 KiB            [emitted]  
         fonts/KaTeX_SansSerif-Regular--fonts.woff   15.8 KiB            [emitted]  
        fonts/KaTeX_SansSerif-Regular--fonts.woff2   13.4 KiB            [emitted]  
             fonts/KaTeX_Script-Regular--fonts.ttf     24 KiB            [emitted]  
            fonts/KaTeX_Script-Regular--fonts.woff   13.1 KiB            [emitted]  
           fonts/KaTeX_Script-Regular--fonts.woff2   11.8 KiB            [emitted]  
              fonts/KaTeX_Size1-Regular--fonts.ttf   12.6 KiB            [emitted]  
              fonts/KaTeX_Size2-Regular--fonts.ttf   11.9 KiB            [emitted]  
              fonts/KaTeX_Size4-Regular--fonts.ttf   10.8 KiB            [emitted]  
         fonts/KaTeX_Typewriter-Regular--fonts.ttf   35.1 KiB            [emitted]  
        fonts/KaTeX_Typewriter-Regular--fonts.woff   19.8 KiB            [emitted]  
       fonts/KaTeX_Typewriter-Regular--fonts.woff2   16.9 KiB            [emitted]  
              fonts/fontawesome-webfont--fonts.eot    162 KiB            [emitted]  
              fonts/fontawesome-webfont--fonts.ttf    162 KiB            [emitted]  
             fonts/fontawesome-webfont--fonts.woff   95.7 KiB            [emitted]  
            fonts/fontawesome-webfont--fonts.woff2   75.4 KiB            [emitted]  
                          fonts/iconfont--icon.eot   21.9 KiB            [emitted]  
                          fonts/iconfont--icon.ttf   21.7 KiB            [emitted]  
                         fonts/iconfont--icon.woff   13.6 KiB            [emitted]  
                       fonts/iconfont--newicon.eot   27.9 KiB            [emitted]  
                       fonts/iconfont--newicon.ttf   27.7 KiB            [emitted]  
                      fonts/iconfont--newicon.woff   17.2 KiB            [emitted]  
  imgs/1e7b63404cd2fb8e6525b2fd4ee4d286--emoji.png   6.83 MiB            [emitted]  
               imgs/fontawesome-webfont--fonts.svg    434 KiB            [emitted]  
                            imgs/grain1--grain.png     46 KiB            [emitted]  
                            imgs/grain4--grain.jpg     80 KiB            [emitted]  
                            imgs/grain5--grain.png    165 KiB            [emitted]  
                           imgs/iconfont--icon.svg   82.9 KiB            [emitted]  
                       imgs/iconfont--mindIcon.svg   28.7 KiB            [emitted]  
                        imgs/iconfont--newicon.svg    128 KiB            [emitted]  
                             imgs/logo--assets.png   28.6 KiB            [emitted]  
                            imgs/orange--theme.png   19.5 KiB            [emitted]  
                                        index.html  455 bytes            [emitted]  
                                       renderer.js   10.6 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [1] multi (webpack)-dev-server/client?http://localhost ./.electron-vue/dev-client ./src/renderer/main.js 52 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 731 bytes {renderer} [built]
  [./node_modules/@iktakahiro/markdown-it-katex/node_modules/katex/dist/katex.min.css] 970 bytes {renderer} [built]
  [./node_modules/markdown-it-icons/dist/index.css] 922 bytes {renderer} [built]
  [./node_modules/quill/dist/quill.bubble.css] 943 bytes {renderer} [built]
  [./node_modules/quill/dist/quill.core.css] 937 bytes {renderer} [built]
  [./node_modules/quill/dist/quill.snow.css] 937 bytes {renderer} [built]
  [./node_modules/strip-ansi/index.js] 161 bytes {renderer} [built]
  [./node_modules/vue/dist/vue.esm.js] 319 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {renderer} [built]
  [./src/renderer/main.js] 1.59 KiB {renderer} [built]
      + 780 hidden modules
  
  WARNING in ./src/renderer/mind/mind.js 543:43-57
  "export 'AutoNumber' (imported as 'cmd') was not found in './command/cmd'
   @ ./src/renderer/components/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editor.vue?vue&type=script&lang=js&)
   @ ./src/renderer/components/editor.vue?vue&type=script&lang=js&
   @ ./src/renderer/components/editor.vue
   @ ./src/renderer/router/index.js
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
  
  ERROR in Template execution failed: ReferenceError: process is not defined
  
  ERROR in   ReferenceError: process is not defined
    
    - index.ejs:11 eval
      [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
    
    - index.ejs:16 module.exports
      [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
    
    - index.js:284 
      [Mark-Mind]/[html-webpack-plugin]/index.js:284:18
    
    - runMicrotasks
    
    - task_queues.js:93 processTicksAndRejections
      internal/process/task_queues.js:93:5
    
  
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.38 MiB       0  
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 8.45 KiB {0} [built]
      [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

┗ ----------------------------

┏ Main Process ---------------

  Hash: 471778851dbca6902c1b
  Version: webpack 4.42.1
  Time: 8810ms
  Built at: 2020/11/20 上午10:35:03
    Asset     Size  Chunks             Chunk Names
  main.js  360 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/babel-runtime/core-js/json/stringify.js] 95 bytes {main} [built]
  [./node_modules/babel-runtime/helpers/classCallCheck.js] 208 bytes {main} [built]
  [./node_modules/babel-runtime/helpers/createClass.js] 904 bytes {main} [built]
  [./node_modules/electron-debug/index.js] 2.46 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]
  [./src/main/index.dev.js] 364 bytes {main} [built]
  [./src/main/index.js] 6.24 KiB {main} [built]
  [./src/main/locales/en.js] 5.1 KiB {main} [built]
  [./src/main/locales/zh.js] 5.08 KiB {main} [built]
  [./src/main/onedrive.js] 15.5 KiB {main} [built]
  [./src/renderer/store/index.js] 317 bytes {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [electron-store] external "electron-store" 42 bytes {main} [built]
  [fs] external "fs" 42 bytes {main} [built]
      + 125 hidden modules
  
  WARNING in ./node_modules/electron-debug/index.js 81:45-58
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js
  
  WARNING in ./node_modules/electron-debug/index.js 84:85-106
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

┗ ----------------------------

┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/4813201f-8e7c-4f3f-9015-542077e4fc42
  For help, see: https://nodejs.org/en/docs/inspector
  
┗ ----------------------------

┏ Electron -------------------

  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
  
┗ ----------------------------

**Comment by MarkMindLtd** [comment]
> 〜：npm运行dev
> 
> > mind@1.1.5 dev /用户/admin/go/src/github.com/MarkMindLtd/Mark-Mind
> > 节点.electron -vue / dev-runner.js
> 
> ```
>      ___                      __                                                                
> ```
> 
> __ / _ \ __ ___ / \ __ _ __ ___ ___ __ __ __ __ __
> / /。`\ \//\ \ / ,.`\ /' ___\ \ \，_ \ /`__ \ / __ `\ /' _ `\ _______ / \ / \ / \ / \\ / / .. \\\\ __ / _ \ _ / \ __ / / \ __ / \ \ \ \ \ \ \ / / \ _ \ / \ / \ \ / _ __**_\ / / | \ \ _ \ / \ **/ \ _**_ \ / _**_ \ _ _**\ _**_ \ \ \ _ \ _ \ \ _ _**/ \ _ \ _ \ _ \ / **__**/ \ _** / \ _ _**/ \ _ **_ / __**/ /**__ / / __**/ /**__ \ \ __ \ _/ / ___/ /_ // //_ / / **/ / **_/ /_ ___ /
> / __ /
> 准备...
> 
> ┏主要流程---------------
> 
> 编译中...
> 
> ┗----------------------------
> 
> ℹ｢wds｣：项目运行在[http：// localhost：9080 /](http://localhost:9080/)
> ℹ ｢wds｣：webpack输出由未定义提供
> ℹ｢wds｣：非Webpack的内容可从/Users/admin/go/src/github.com/MarkMindLtd/Mark-Mind/ served呈现
> 程序-----------
> 
> Hash: a1be9a2583a4e5f3ffe9
> Version: webpack 4.42.1
> Time: 8692ms
> Built at: 2020/11/20 上午10:35:03
> Asset Size Chunks Chunk Names
> 0.js 176 KiB 0 [emitted]
> 1.js 272 KiB 1 [emitted]
> 2.js 167 KiB 2 [emitted]
> 3.js 55.2 KiB 3 [emitted]
> 4.js 45.4 KiB 4 [emitted]
> 5.js 30.1 KiB 5 [emitted]
> fonts/KaTeX_AMS-Regular--fonts.ttf 69.3 KiB [emitted]
> fonts/KaTeX_AMS-Regular--fonts.woff 38 KiB [emitted]
> fonts/KaTeX_AMS-Regular--fonts.woff2 32.2 KiB [emitted]
> fonts/KaTeX_Caligraphic-Bold--fonts.ttf 18.9 KiB [emitted]
> fonts/KaTeX_Caligraphic-Bold--fonts.woff 11.4 KiB [emitted]
> fonts/KaTeX_Caligraphic-Bold--fonts.woff2 10.2 KiB [emitted]
> fonts/KaTeX_Caligraphic-Regular--fonts.ttf 18.2 KiB [emitted]
> fonts/KaTeX_Caligraphic-Regular--fonts.woff 11.2 KiB [emitted]
> fonts/KaTeX_Caligraphic-Regular--fonts.woff2 10 KiB [emitted]
> fonts/KaTeX_Fraktur-Bold--fonts.ttf 34.8 KiB [emitted]
> fonts/KaTeX_Fraktur-Bold--fonts.woff 22.1 KiB [emitted]
> fonts/KaTeX_Fraktur-Bold--fonts.woff2 19.9 KiB [emitted]
> fonts/KaTeX_Fraktur-Regular--fonts.ttf 33.5 KiB [emitted]
> fonts/KaTeX_Fraktur-Regular--fonts.woff 21.6 KiB [emitted]
> fonts/KaTeX_Fraktur-Regular--fonts.woff2 19.3 KiB [emitted]
> fonts/KaTeX_Main-Bold--fonts.ttf 59.4 KiB [emitted]
> fonts/KaTeX_Main-Bold--fonts.woff 34.6 KiB [emitted]
> fonts/KaTeX_Main-Bold--fonts.woff2 29.5 KiB [emitted]
> fonts/KaTeX_Main-BoldItalic--fonts.ttf 43.5 KiB [emitted]
> fonts/KaTeX_Main-BoldItalic--fonts.woff 24.8 KiB [emitted]
> fonts/KaTeX_Main-BoldItalic--fonts.woff2 21.4 KiB [emitted]
> fonts/KaTeX_Main-Italic--fonts.ttf 46.5 KiB [emitted]
> fonts/KaTeX_Main-Italic--fonts.woff 25.6 KiB [emitted]
> fonts/KaTeX_Main-Italic--fonts.woff2 22.2 KiB [emitted]
> fonts/KaTeX_Main-Regular--fonts.ttf 67.9 KiB [emitted]
> fonts/KaTeX_Main-Regular--fonts.woff 37.2 KiB [emitted]
> fonts/KaTeX_Main-Regular--fonts.woff2 31.7 KiB [emitted]
> fonts/KaTeX_Math-BoldItalic--fonts.ttf 38.4 KiB [emitted]
> fonts/KaTeX_Math-BoldItalic--fonts.woff 21.8 KiB [emitted]
> fonts/KaTeX_Math-BoldItalic--fonts.woff2 19.3 KiB [emitted]
> fonts/KaTeX_Math-Italic--fonts.ttf 40 KiB [emitted]
> fonts/KaTeX_Math-Italic--fonts.woff 22.3 KiB [emitted]
> fonts/KaTeX_Math-Italic--fonts.woff2 19.6 KiB [emitted]
> fonts/KaTeX_SansSerif-Bold--fonts.ttf 32.9 KiB [emitted]
> fonts/KaTeX_SansSerif-Bold--fonts.woff 18.1 KiB [emitted]
> fonts/KaTeX_SansSerif-Bold--fonts.woff2 15.4 KiB [emitted]
> fonts/KaTeX_SansSerif-Italic--fonts.ttf 30.2 KiB [emitted]
> fonts/KaTeX_SansSerif-Italic--fonts.woff 17.2 KiB [emitted]
> fonts/KaTeX_SansSerif-Italic--fonts.woff2 14.7 KiB [emitted]
> fonts/KaTeX_SansSerif-Regular--fonts.ttf 29.1 KiB [emitted]
> fonts/KaTeX_SansSerif-Regular--fonts.woff 15.8 KiB [emitted]
> fonts/KaTeX_SansSerif-Regular--fonts.woff2 13.4 KiB [emitted]
> fonts/KaTeX_Script-Regular--fonts.ttf 24 KiB [emitted]
> fonts/KaTeX_Script-Regular--fonts.woff 13.1 KiB [emitted]
> fonts/KaTeX_Script-Regular--fonts.woff2 11.8 KiB [emitted]
> fonts/KaTeX_Size1-Regular--fonts.ttf 12.6 KiB [emitted]
> fonts/KaTeX_Size2-Regular--fonts.ttf 11.9 KiB [emitted]
> fonts/KaTeX_Size4-Regular--fonts.ttf 10.8 KiB [emitted]
> fonts/KaTeX_Typewriter-Regular--fonts.ttf 35.1 KiB [emitted]
> fonts/KaTeX_Typewriter-Regular--fonts.woff 19.8 KiB [emitted]
> fonts/KaTeX_Typewriter-Regular--fonts.woff2 16.9 KiB [emitted]
> fonts/fontawesome-webfont--fonts.eot 162 KiB [emitted]
> fonts/fontawesome-webfont--fonts.ttf 162 KiB [emitted]
> fonts/fontawesome-webfont--fonts.woff 95.7 KiB [emitted]
> fonts/fontawesome-webfont--fonts.woff2 75.4 KiB [emitted]
> fonts/iconfont--icon.eot 21.9 KiB [emitted]
> fonts/iconfont--icon.ttf 21.7 KiB [emitted]
> fonts/iconfont--icon.woff 13.6 KiB [emitted]
> fonts/iconfont--newicon.eot 27.9 KiB [emitted]
> fonts/iconfont--newicon.ttf 27.7 KiB [emitted]
> fonts/iconfont--newicon.woff 17.2 KiB [emitted]
> imgs/1e7b63404cd2fb8e6525b2fd4ee4d286--emoji.png 6.83 MiB [emitted]
> imgs/fontawesome-webfont--fonts.svg 434 KiB [emitted]
> imgs/grain1--grain.png 46 KiB [emitted]
> imgs/grain4--grain.jpg 80 KiB [emitted]
> imgs/grain5--grain.png 165 KiB [emitted]
> imgs/iconfont--icon.svg 82.9 KiB [emitted]
> imgs/iconfont--mindIcon.svg 28.7 KiB [emitted]
> imgs/iconfont--newicon.svg 128 KiB [emitted]
> imgs/logo--assets.png 28.6 KiB [emitted]
> imgs/orange--theme.png 19.5 KiB [emitted]
> index.html 455 bytes [emitted]
> renderer.js 10.6 MiB renderer [emitted] renderer
> Entrypoint renderer = renderer.js
> [1] multi (webpack)-dev-server/client?http://localhost ./.electron-vue/dev-client ./src/renderer/main.js 52 bytes {renderer} [built]
> [./.electron-vue/dev-client.js] 731 bytes {renderer} [built]
> [./node_modules/@iktakahiro/markdown-it-katex/node_modules/katex/dist/katex.min.css] 970 bytes {renderer} [built]
> [./node_modules/markdown-it-icons/dist/index.css] 922 bytes {renderer} [built]
> [./node_modules/quill/dist/quill.bubble.css] 943 bytes {renderer} [built]
> [./node_modules/quill/dist/quill.core.css] 937 bytes {renderer} [built]
> [./node_modules/quill/dist/quill.snow.css] 937 bytes {renderer} [built]
> [./node_modules/strip-ansi/index.js] 161 bytes {renderer} [built]
> [./node_modules/vue/dist/vue.esm.js] 319 KiB {renderer} [built]
> [./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {renderer} [built]
> [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {renderer} [built]
> [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {renderer} [built]
> [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {renderer} [built]
> [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {renderer} [built]
> [./src/renderer/main.js] 1.59 KiB {renderer} [built]
> + 780 hidden modules
> 
> WARNING in ./src/renderer/mind/mind.js 543:43-57
> "export 'AutoNumber' (imported as 'cmd') was not found in './command/cmd'
> @ ./src/renderer/components/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editor.vue?vue&type=script&lang=js&)
> @ ./src/renderer/components/editor.vue?vue&type=script&lang=js&
> @ ./src/renderer/components/editor.vue
> @ ./src/renderer/router/index.js
> @ ./src/renderer/main.js
> @ multi ./.electron-vue/dev-client ./src/renderer/main.js
> 
> ERROR in Template execution failed: ReferenceError: process is not defined
> 
> ERROR in ReferenceError: process is not defined
> 
> ```
> - index.ejs:11 eval
>   [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
> 
> - index.ejs:16 module.exports
>   [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
> 
> - index.js:284 
>   [Mark-Mind]/[html-webpack-plugin]/index.js:284:18
> 
> - runMicrotasks
> 
> - task_queues.js:93 processTicksAndRejections
>   internal/process/task_queues.js:93:5
> ```
> 
> Child html-webpack-plugin for "index.html":
> Asset Size Chunks Chunk Names
> index.html 1.38 MiB 0
> Entrypoint undefined = index.html
> [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 8.45 KiB {0} [built]
> [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
> [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
> 
> ┗ ----------------------------
> 
> ┏ Main Process ---------------
> 
> Hash: 471778851dbca6902c1b
> Version: webpack 4.42.1
> Time: 8810ms
> Built at: 2020/11/20 上午10:35:03
> Asset Size Chunks Chunk Names
> main.js 360 KiB main [emitted] main
> Entrypoint main = main.js
> [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
> [./node_modules/babel-runtime/core-js/json/stringify.js] 95 bytes {main} [built]
> [./node_modules/babel-runtime/helpers/classCallCheck.js] 208 bytes {main} [built]
> [./node_modules/babel-runtime/helpers/createClass.js] 904 bytes {main} [built]
> [./node_modules/electron-debug/index.js] 2.46 KiB {main} [built]
> [./node_modules/electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]
> [./src/main/index.dev.js] 364 bytes {main} [built]
> [./src/main/index.js] 6.24 KiB {main} [built]
> [./src/main/locales/en.js] 5.1 KiB {main} [built]
> [./src/main/locales/zh.js] 5.08 KiB {main} [built]
> [./src/main/onedrive.js] 15.5 KiB {main} [built]
> [./src/renderer/store/index.js] 317 bytes {main} [built]
> [electron] external "electron" 42 bytes {main} [built]
> [electron-store] external "electron-store" 42 bytes {main} [built]
> [fs] external "fs" 42 bytes {main} [built]
> + 125 hidden modules
> 
> WARNING in ./node_modules/electron-debug/index.js 81:45-58
> Critical dependency: the request of a dependency is an expression
> @ ./src/main/index.dev.js
> @ multi ./src/main/index.dev.js ./src/main/index.js
> 
> WARNING in ./node_modules/electron-debug/index.js 84:85-106
> Critical dependency: the request of a dependency is an expression
> @ ./src/main/index.dev.js
> @ multi ./src/main/index.dev.js ./src/main/index.js
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
> Debugger listening on ws://127.0.0.1:5858/4813201f-8e7c-4f3f-9015-542077e4fc42
> For help, see: https://nodejs.org/en/docs/inspector
> 
> ┗ ----------------------------
> 
> ┏ Electron -------------------
> 
> （电子）app.allowRendererProcessReuse的默认值已弃用，当前为“ false”。在电子9中它将更改为“ true”。有关更多信息，请检查[electronic / electron＃18397](https://github.com/electron/electron/issues/18397)
> 
> ┗----------------------------

已解决
