### ISSUE TITLE
联系线好像只能在初始化的时候变化它的曲线

### ISSUE THREAD

**Issue by lgc653** [MarkMindLtd/Mark-Mind#18]
软件非常好用，十分感谢。
联系线好像只能在初始化的时候变化它的曲线，之后再想修改曲线好像就不行了，不知是我不会操作还是本来就有这个问题

**Comment by MarkMindLtd** [comment]
点击链接的节点，可以修改线段

**Comment by MarkMindLtd** [comment]
![3](https://user-images.githubusercontent.com/18719494/103617029-6aaf5280-4f68-11eb-9cd1-be1bedf28c60.gif)
