### ISSUE TITLE
plantuml generated image not cached/can not export to kittymind

### ISSUE THREAD

**Issue by huangwu1** [MarkMindLtd/Mark-Mind#23]
Sometimes we need privacy plantuml support ,now we can run a plantuml server using docker locally, but when the plantuml server shutdown, reopen a mind file can not show plantuml image even no edit action happened at all. 
At the same time , when export a normally showned mind file with plantuml images  to a kittymind file , no plantuml result image kept, but kittymind cannot convert the plantuml script  to a image. Can we just keep both image/plantuml script ?

**Comment by MarkMindLtd** [comment]
if you want to keep image,you should add image to node,like this
![5](https://user-images.githubusercontent.com/18719494/104157656-8a41f180-5426-11eb-9d8c-3f57b4431b05.gif)

**Comment by MarkMindLtd** [comment]
In fact, the mind file is a compressed file. You can change the suffix to zip,then open it
