### ISSUE TITLE
Copy and paste a word overwrite the word I filled in

### ISSUE THREAD

**Issue by w568405096** [MarkMindLtd/Mark-Mind#24]
Copy and paste a word that I want to join with the one I filled in earlier, but actually the pasted word will directly overwrite the word I filled in

**Comment by MarkMindLtd** [comment]
ctrl + shift + v

**Comment by MarkMindLtd** [comment]
ctrl + v  

turn html to markdown

**Comment by MarkMindLtd** [comment]
https://github.com/MarkMindLtd/Mark-Mind/releases/tag/v1.1.9
