### ISSUE TITLE
可以和 MindMaster 的文件互导吗？

### ISSUE THREAD

**Issue by taotieren** [MarkMindLtd/Mark-Mind#31]
可以和 [MindMaster](https://www.edrawsoft.cn/download/mindmaster/all/) 的文件互导吗？

**Comment by MarkMindLtd** [comment]
之后会支持 Mindmaster 导入，使用本软件导出freemind ，可以导入Mindmaster

**Comment by taotieren** [comment]
但是 mindmaster 不能导出 freemind 2021年2月26日 12:56，ckminder <notifications@github.com>写道：

之后会支持 Mindmaster 导入，使用本软件导出freemind ，可以导入Mindmaster

**Comment by taotieren** [comment]
@MarkMindLtd 使用感觉不错，有优惠码吗？想买一个支持一下。

**Comment by taotieren** [comment]
@MarkMindLtd 网站是 http 使用 Chrome 打不开。使用 FireFox 强制用 http 模式可以打开。什么时候会支持 https 呢？

**Comment by taotieren** [comment]
@MarkMindLtd 使用 GitHub  登录返回 500 错误。

**Comment by MarkMindLtd** [comment]
github 接口似乎修改了，等最近修复一下
