### ISSUE TITLE
Mark-mind AUR 包

### ISSUE THREAD

**Issue by taotieren** [MarkMindLtd/Mark-Mind#34]

**Comment by taotieren** [comment]
Mark-Mind 有计划提供 AUR 包吗？

**Comment by taotieren** [comment]
```bash
https://github.com/pavlobu/deskreen/blob/master/.github/workflows/post-release-publish.yml
```
AUR 的打包脚本可以参考这部分的

**Comment by MarkMindLtd** [comment]
ok,谢谢

**Comment by taotieren** [comment]
> ok,谢谢

1. 需要先创建一个 aur 的 ssh 密钥并和 ArchLinux 的账户关联。
2. 从 AUR `git clone ssh://aur@aur.archlinux.org/mark-mind.git` 创建 `mark-mind` 仓库
3. `git clone https://aur.archlinux.org/deskreen.git` 将 `PKGBUILD` `*.desktop`  复制到 `mark-mind` 并进行相关包名替换
4. 在 `mark-mind` 仓库修改完后，生成` .SRCINFO` 方式 `makepkg makepkg --printsrcinfo > .SRCINFO`
5. 可以参考我这边的 AUR 包的打包和测试的 Actions `https://github.com/taotieren/arch_aur/blob/main/.github/workflows/CI.yml`
6. 测试通过后上传到 AUR 仓库
........................

**Comment by taotieren** [comment]
提交了 Mark-Mind 的 AUR 软件包
```bash
https://aur.archlinux.org/packages/mark-mind/
```

**Comment by adaaaaaa** [comment]
大佬快更新啦，现在1.3.1了。。。🤪

**Comment by taotieren** [comment]
已更新2021年7月20日 15:00，adaaaaaa ***@***.***>写道：

大佬快更新啦，现在1.3.1了。。。🤪
