### ISSUE TITLE
Can not see the rendered result

### ISSUE THREAD

**Issue by aaa55856** [MarkMindLtd/Mark-Mind#36]
Hello, my installed program on my windows 10 PC can not render the result, but the app in Android works nicely.

![error](https://user-images.githubusercontent.com/32005753/109491659-d0c9d900-7ac4-11eb-87c5-ba05c2bb32ca.png)

If I miss something essential?

**Comment by MarkMindLtd** [comment]
please open markdown
![1](https://user-images.githubusercontent.com/18719494/109591127-efbd7f00-7b47-11eb-9982-c13528a627ec.png)
![2](https://user-images.githubusercontent.com/18719494/109591132-f21fd900-7b47-11eb-9282-c2e4b2e9980e.png)

**Comment by aaa55856** [comment]
Oops! Thank you very much! It works perfectly now. 😄
