### ISSUE TITLE
做了一个思维导图，但是打开mind文件后白屏

### ISSUE THREAD

**Issue by kuimig** [MarkMindLtd/Mark-Mind#39]
大小在270MB....因为图比较多 怎么办？

**Comment by MarkMindLtd** [comment]
原因
打开软件会加载缓存，这个导图太大，可能需要等一段时间，如果不行，使用以下方法:

在c盘 搜索 mind 文件夹 其中有个vuex.json文件，这个是缓存，删除掉之后，重启一下软件

**Comment by kuimig** [comment]
![image](https://user-images.githubusercontent.com/57479948/111285565-3d73d480-867c-11eb-82ee-76071b4be012.png)
我重新装了 只有vk_swiftshader_icd.json c盘找不到vuex.json

**Comment by kuimig** [comment]
找到了。。。谢谢

**Comment by kuimig** [comment]
![image](https://user-images.githubusercontent.com/57479948/111286709-6fd20180-867d-11eb-81a2-266265e2f547.png)
但是两个位置都有 都要删除麽

**Comment by kuimig** [comment]
![image](https://user-images.githubusercontent.com/57479948/111287238-fbe42900-867d-11eb-8370-0605c6d7e347.png)
重启之后重新打开，这个缓存文件一直是这个大小文件尺寸也没有变化。还是一直白屏

**Comment by kuimig** [comment]
每次加载完cache大小一直是132.894kb
![image](https://user-images.githubusercontent.com/57479948/111288141-e02d5280-867e-11eb-9b66-3230291f5613.png)
实际大小有
![image](https://user-images.githubusercontent.com/57479948/111288199-ede2d800-867e-11eb-8c90-31a01c2bd3f2.png)

**Comment by kuimig** [comment]
刚试了下mind文件夹全删了，重新打开文件，vuex.json还是132.894kb大小。。。。。是不是限制大小了？

**Comment by MarkMindLtd** [comment]
没限制，是软件自己生成的，只要软件能用就行了，平时不用管

**Comment by MarkMindLtd** [comment]
删除mind文件夹下的vuex.json

**Comment by MarkMindLtd** [comment]
软件可能无法支持这么大的思维导图，不知可否将导图去除隐私之后发给我，我可以用于测试，并尝试支持该导图，我的邮箱ckminder@163.com

**Comment by kuimig** [comment]
> 软件可能无法支持这么大的思维导图，不知可否将导图去除隐私之后发给我，我可以用于测试，并尝试支持该导图，我的邮箱[ckminder@163.com](mailto:ckminder@163.com)

明天早上发您我现在回家了

**Comment by kuimig** [comment]
> 软件可能无法支持这么大的思维导图，不知可否将导图去除隐私之后发给我，我可以用于测试，并尝试支持该导图，我的邮箱[ckminder@163.com](mailto:ckminder@163.com)

已经发给您了，小哥注意查收哈，这个麻烦麽？

**Comment by MarkMindLtd** [comment]
收到了～
