### ISSUE TITLE
windows 版本tag左侧的备注里面绿色的对勾点了没有反应

### ISSUE THREAD

**Issue by forxhunter** [MarkMindLtd/Mark-Mind#49]
版本	Windows 10 家庭中文版
版本号	20H2
安装日期	‎2021/‎3/‎7
操作系统内部版本	19042.985
序列号	PF2LQ8P6
体验	Windows Feature Experience Pack 120.2212.2020.0

**Comment by forxhunter** [comment]
此外，想问一下这种点一下会出现提示的《备注》是怎么加的呢？快捷键是什么呢，比如图片里面最右边的那种
![image](https://user-images.githubusercontent.com/41635675/119466580-56cd8700-bd77-11eb-8a67-1e4afc2ed74e.png)

**Comment by MarkMindCkm** [comment]
> 此外，想问一下这种点一下会出现提示的《备注》是怎么加的呢？快捷键是什么呢，比如图片里面最右边的那种
> ![image](https://user-images.githubusercontent.com/41635675/119466580-56cd8700-bd77-11eb-8a67-1e4afc2ed74e.png)

这个就是备注，就是这个问题导致的，无法添加备注

**Comment by forxhunter** [comment]
> > 此外，想问一下这种点一下会出现提示的《备注》是怎么加的呢？快捷键是什么呢，比如图片里面最右边的那种
> > ![image](https://user-images.githubusercontent.com/41635675/119466580-56cd8700-bd77-11eb-8a67-1e4afc2ed74e.png)
> 
> 这个就是备注，就是这个问题导致的，无法添加备注

那想问一下，这个bug目前有没有什么解决方案呢，比如说mark down模式下的快捷键什么的

**Comment by MarkMindCkm** [comment]
> > > 此外，想问一下这种点一下会出现提示的《备注》是怎么加的呢？快捷键是什么呢，比如图片里面最右边的那种
> > > ![image](https://user-images.githubusercontent.com/41635675/119466580-56cd8700-bd77-11eb-8a67-1e4afc2ed74e.png)
> > 
> > 
> > 这个就是备注，就是这个问题导致的，无法添加备注
> 
> 那想问一下，这个bug目前有没有什么解决方案呢，比如说mark down模式下的快捷键什么的

已修复，已发版
