### ISSUE TITLE
windows版本快捷键Crtl+S默认出现保存pdf版本

### ISSUE THREAD

**Issue by forxhunter** [MarkMindLtd/Mark-Mind#50]
![image](https://user-images.githubusercontent.com/41635675/119587110-97bdae00-be00-11eb-959d-4b9ab3f621a9.png)

**Comment by MarkMindCkm** [comment]
这是集成pdf viewer 导致的问题

**Comment by MarkMindCkm** [comment]
已解决，已发版

**Comment by forxhunter** [comment]
谢谢
