### ISSUE TITLE
mac client

### ISSUE THREAD

**Issue by LastRitter** [MarkMindLtd/Mark-Mind#8]
hello, can you provide mac client release ? thank you please.

**Comment by MarkMindLtd** [comment]
https://github.com/MarkMindLtd/Mark-Mind/releases/tag/1.1.6

**Comment by mapleafly** [comment]
hi, can u make a linux releas? eg ubuntu or linuxmint

**Comment by MarkMindLtd** [comment]
https://github.com/MarkMindLtd/Mark-Mind/releases/download/1.1.6/Mark.Mind.1.1.6.AppImage
